import { Card, CardContent } from '../components/ui/card'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '../components/ui/accordion'

// Full list of locations grouped by province
const locationsByProvince = {
	'Balochistan': [
		'Lasbella',
		'Kehniwari',
		'Lakhra',
		'Wayara',
		'Sohbatpur',
		'Jhanda talla',
		'Kalat',
		'Naseerabad',
		'Khuzdar',
		'Jhal magsi',
		'Noshki',
		'Muslim Bagh',
		'Hanna',
		'Juddo, Badin',
		'Khanpur Pull, Jaffarabad',
		'Saifullah Canal',
		'Qambae Shahdadkot',
		'Kharan',
		'Kushdar',
		'Bela',
		'Musa Khele',
		'Pishin',
		'Naseera bad',
		'Jaffarabad',
		'Guzdar',
		'Uthal',
		'Nuashahro Feroze',
		'Shaban',
		'Kalhotpur',
		'Chowki jamali',
		'Sohbatpura',
		'Dera Murad Jamali',
		'Jhudel Shakh',
		'Foleji',
		'Gandakha',
		'Bhand',
		'Hazoor Bux',
	],
	'Punjab': [
		'Hajipur',
		'Miranpur',
		'Nurpur',
		'Bakhipur',
		'Bumbli',
		'Lundhi',
		'Saeedan',
		'Kachagarh',
		'Baisti khawand',
		'Mozzo wah',
		'Machka',
		'Baisti Maindhra',
		'Ozmaan',
		'Baisti dostan',
		'Chak mat 1',
		'Chak mat 2',
		'Mohalaa lohran',
		'Rojhan',
		'Shehr Kachi abadi',
		'Gahr Kachi abadi',
		'Baisti ghunah arain',
		'Baisti Hussain bux',
		'Nazr baisti',
		'Kaicha',
		'Baisti tahlian',
		'Baisti haji',
		'Shahid mizari',
		'Baisti sakhi bux Railway phatak',
		'Baisti Gola miranpur',
		'Baisti bala chanrni',
		'Dera dildaar',
		'Baisti naseeb e bad',
		'Layyah',
		'Haji mora',
		'Rajanpur',
		'Fazilpur',
		'Teekan',
		'Taunsa',
		'Dera Ghazi Khan',
		'Baisti dreshak',
		'Baisti surhani',
		'Baisti smati',
		'Baisti sayal',
		'UC Sukar',
		'Mangrotha',
		'West nEas',
		'Tebi qesrani',
		'UC nutkani',
		'Dagerwali,siknderabad',
		'Vohova',
		'Jhangi',
		'Basti Langah',
		'Kulachi',
		'Gulowala',
		'Moga',
		'Ganb',
		'Dakhana',
		'Noor ahmad',
		'Koh E Sulman',
		// Default relief cities in Punjab
		'Lahore',
		'AliPur',
		'Chiniot',
		'Gujrat',
		'Jhang',
		'Multan',
		'Muzafargarh',
		'Pakpattan',
		'Pindi Bhatiyan Hafiz Abad',
		'Sialkot',
	],
	'KPK': [
		'Nowshera',
		'Pushtoon Gari',
		'Bhagpai',
		'Hussain Khan Ghunio',
		'Dera Ismail Khan',
		'Muhammad Achar Khaskheli',
		'Tehseel Parwa',
		'Nowshera Kalan',
		'Tehseel Paharpur',
		'Tehseel Kulachi',
		'Charsadda',
		'Bahrain',
		'Matiltan',
		'Madyan',
		'Ripri',
		'Chakdum',
		'Station Kach',
		'Geran Baloch',
		'Swat',
		'Mankiyal',
		'Cham Ghadi',
		'Pushmal',
		'Torwal',
		'Asreath',
		'Kohistan Dasu',
		'Dobaer',
		'Khalee',
		'Kalam',
		'Amaan gar',
		'Misalabad',
		'Tank city',
		'Buner',
		'Mingora',
		'Shangla',
	],
	'Sindh': [
		'Sakhi deen Pannah',
		'Sahib Khan Jiskani',
		'Sher Muhammad Magsi',
		'Ghulam Sarwar Mirrani',
		'Lal Bux Sial',
		'Mahar Tare',
		'Khanan Buriro',
		'Ali Dino Tumrani',
		'Haji Jan Muhammad Tumrani',
		'Syed Waryal Shah',
		'Sagyoon',
		'Faiz Ganj',
		'Miskeen Pur Village',
		'Nasirabad',
		'Hassan Wahan District Larkana',
		'Village Dorai wara Shaikh District Larkana',
		'Rasheed Wagan district Larkana',
		'Mumtaz Colony district Larkana',
		'Village Bachal Shah District Larkana',
		'Niaz Muhammad kapri',
		'Fazal Muhammad Kapri',
		'Shafi Sansi Punjabi',
		'Khuda Bux Laghari',
		'Din Muhammad Kapri',
		'UC Ghazi Khan',
		'UC Ghulam Shah',
		'UC Halepota',
		'UC Khairpur Gamboh',
		'UC Malkani sharif',
		'UC Saman Sarkar',
		'Shahnawaz',
		'Jamshoro',
		'Tharparker',
		'Ghotki',
		'Balhreji Village',
		'Dadu',
		// Default in Sindh
		'Karachi',
	],
	'Gilgit-Baltistan': [
		'Buber Puniyal',
		'Diamer',
		'Immit',
		'Bagrot',
		'Yasin',
		'Nagar',
		'Ishkomen',
		// Default in Gilgit
		'Ghizer',
		'Gilgit',
		'Shighar',
		'Skardu',
	],
}

export default function Locations() {
	return (
		<Accordion type='single' collapsible className='w-full space-y-8'>
			{Object.entries(locationsByProvince).map(([province, cities]) => (
				<AccordionItem value={province} key={province}>
					<AccordionTrigger className='text-left'>
						<h2 className='text-2xl font-bold flex-grow'>{province}</h2>
						<p className='text-muted-foreground'>({cities.length} locations)</p>
					</AccordionTrigger>
					<AccordionContent>
						<div className='grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid  -cols-5 gap-4 mt-4'>
							{cities.map((city) => (
								<Card key={city}>
									<CardContent className='p-4'>
										<h3 className='font-semibold'>{city}</h3>
									</CardContent>
								</Card>
							))}
						</div>
					</AccordionContent>
				</AccordionItem>
			))}
		</Accordion>
	)
}
